services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 6000:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  node:
    container_name: node_app_image
    build: .
    ports:
      - 5555:5000
    env_file:
      - .env
    depends_on:
      - db
  
volumes:
  pg: